CREATE TABLE  `actm`.`CERVEJAS` (
`ID_CERVEJA`            INT NOT NULL AUTO_INCREMENT PRIMARY KEY
,  `DESCRICAO_CERVEJA`  VARCHAR( 50 )   NOT NULL 
,  `HBV`                DECIMAL( 8, 3 ) NOT NULL 
,  `IBU`                DECIMAL( 8, 3 ) NOT NULL 
,  `PRATO_CERVEJA`      INT NULL 
,  `TACA_CERVEJA`       INT NULL 
,  `CERVEJARIA_CERVEJA` INT NOT NULL
) ENGINE = INNODB;

CREATE TABLE  `actm`.`CERVEJARIA` (
`ID_CERVEJARIA`           INT NOT NULL AUTO_INCREMENT 
,  `DESCRICAO_CERVEJARIA` VARCHAR( 50 ) NOT NULL 
PRIMARY KEY (  `ID_CERVEJARIA` )
) ENGINE = INNODB;

CREATE TABLE  `actm`.`ESTILOS` (
`ID_ESTILO`        INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`DESCRICAO_ESTILO` VARCHAR( 50 ) NOT NULL
) ENGINE = INNODB;


CREATE TABLE  `actm`.`PRATOS` (
`ID_PRATO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`DESCRICAO_PRATO` TEXT NOT NULL
) ENGINE = INNODB;

CREATE TABLE  `actm`.`tacas` (
`ID_TACA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`DESCRICAO_TACA` VARCHAR( 35 ) NOT NULL
) ENGINE = INNODB;

